const getters = {
  //user
  token: state => state.user.token,
  userId: state => state.user.userId,
  userInfo: state => state.user.userInfo,
  userOrderList: state => state.user.userOrderList,
  vipInfo:state=>state.user.vipInfo,
  hotelListLoading: state => state.hotel.hotelListLoading,
  hotelList: state => state.hotel.hotelList,
  favList:state => state.user.favList,
  favListLoading: state => state.user.favListLoading,
  addSuccess:state =>state.user.addSuccess,
  deleteSuccess:state =>state.user.deleteSuccess,
  currentHotelInfo: state => state.hotel.currentHotelInfo,
  currentHotelId: state => state.hotel.currentHotelId,
  orderModalVisible: state => state.hotel.orderModalVisible,
  currentOrderRoom: state => state.hotel.currentOrderRoom,
  orderMatchCouponList: state => state.hotel.orderMatchCouponList,
  hotelCouponList:state=>state.hotel.hotelCouponList,
  userOrderDetailVisible: state =>state.user.userOrderDetailVisible,
  userOrderDetail: state => state.user.userOrderDetail,
  makeEvaluationVisible:state=>state.user.makeEvaluationVisible,
  evaluatedHotelName:state=>state.user.evaluatedHotelName,
  evaluations:state=>state.hotel.evaluations,
  //admin
  managerList: state => state.admin.managerList,
  clientList: state => state.admin.clientList,
  saleMenList: state => state.admin.saleMenList,
  addManagerModelVisible: state => state.admin.addManagerModelVisible,
  addManagerParams: state => state.admin.addManagerParams,
  addSaleMenModelVisible: state => state.admin.addSaleMenModelVisible,
  addSaleMenParams: state => state.admin.addSaleMenParams,
  adminAddHotelModelVisible: state=>state.admin.adminAddHotelModelVisible,
  adminAddHotelParams: state=>state.admin.adminAddHotelParams,
  checkUserId:state=>state.admin.checkUserId,
  checkUserInfo:state=>state.admin.checkUserInfo,
  photoHotelId:state=>state.admin.photoHotelId,
  addHotelPhotoVisible:state=>state.admin.addHotelPhotoVisible,

  //hotelManager
  orderList: state => state.hotelManager.orderList,
  addRoomModalVisible: state => state.hotelManager.addRoomModalVisible,
  couponVisible: state => state.hotelManager.couponVisible,
  addCouponVisible: state => state.hotelManager.addCouponVisible,
  managerHotelId: state => state.hotelManager.managerHotelId,
  managerHotelInfo: state => state.hotelManager.managerHotelInfo,
  couponList: state => state.hotelManager.couponList,
  couponDetailVisible: state =>state.hotelManager.couponDetailVisible,
  couponDetail: state => state.hotelManager.couponDetail,
  //saleMen
  exceptionOrderList: state => state.saleMen.exceptionOrderList,
  websiteCouponList: state => state.saleMen.websiteCouponList,
  addWebsiteCouponModalVisible: state => state.saleMen.addWebsiteCouponModalVisible,
}
  
  export default getters